# Generated by Django 4.2.16 on 2024-11-03 15:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0002_recipeingredient_unique_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight_ready',
            field=models.PositiveIntegerField(),
        ),
    ]
